name: Build module

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: bcm2835
            arch: arm
            defconfig: bcm2835_defconfig
            kernel: kernel

          - name: arm64
            arch: arm64
            defconfig: defconfig
            kernel: kernel8

          - name: bcmrpi
            arch: arm
            defconfig: bcmrpi_defconfig
            kernel: kernel

          - name: bcm2709
            arch: arm
            defconfig: bcm2709_defconfig
            kernel: kernel7

          - name: bcm2711
            arch: arm
            defconfig: bcm2711_defconfig
            kernel: kernel7l

          - name: bcm2711_arm64
            arch: arm64
            defconfig: bcm2711_defconfig
            kernel: kernel8

          - name: bcm2712
            arch: arm64
            defconfig: bcm2712_defconfig
            kernel: kernel_2712

    steps:
    - name: Update install
      run:
        sudo apt-get update

    - name: Install toolchain
      run:
        if [[ "${{matrix.arch}}" == "arm64" ]]; then
          sudo apt-get install gcc-aarch64-linux-gnu;
        else
          sudo apt-get install gcc-arm-linux-gnueabihf;
        fi
      timeout-minutes: 5

    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
        clean: true
        
    - uses: actions/download-artifact@v4
      with:
        name: ${{matrix.arch}}_build
        github-token: ${{ secrets.GITHUB_TOKEN }} # token with actions:read permissions on target repo
        repository: raspberrypi/linux
        run-id: 12020017288

    - name: Unpack Kernel
      run: |
        unzip -d kernel ${{matrix.arch}}_build.zip
        tar -xf 

    - name: Build module for ${{matrix.name}}
      run: |
        mkdir ${{github.workspace}}/build
        export ARCH=${{matrix.arch}}
        if [[ "$ARCH" == "arm64" ]]; then
          export CROSS_COMPILE=aarch64-linux-gnu-
        else
          export CROSS_COMPILE=arm-linux-gnueabihf-
        fi
        make M=${{github.workspace}} modules
        
    - name: Upload module
      uses: actions/upload-artifact@v4
      with:
        name: amba-pl011-nofifo-${{matrix.name}}.ko
        path: ${{github.workspace}}/amba-pl011-nofifo.ko
        retention-days: 90
